<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>TemplateEngine</RootNamespace>
		<AssemblyName>TemplateEngine</AssemblyName>

		<AllowUnsafeBlocks>false</AllowUnsafeBlocks>
		<Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>

		<PackageId>Sniz.HtmlTemplateEngine</PackageId>
		<Version>1.1.0</Version>
		<Authors>Nizamuddien TI(nizambajal@gmail.com)</Authors>
		<Company>Sniz</Company>
		<Description>
			Lightweight HTML template engine for C# with Handlebars-like syntax,
			supporting if/else, loops, formatting, metadata, and nested templates.
		</Description>
		<PackageTags>
			html;template;handlebars;templating;engine
		</PackageTags>

		<RepositoryUrl>
			https://github.com/nizambajal/HtmlTemplateEngine
		</RepositoryUrl>

		<PackageProjectUrl>
			https://github.com/nizambajal/HtmlTemplateEngine
		</PackageProjectUrl>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<PackageReleaseNotes>
			Added support for untyped models:
			- JsonElement
			- Dictionary&lt;string, object&gt;
			- ExpandoObject

			Added null-safe property access support.
			Improved template rendering reliability.
		</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md"
			  Pack="true"
			  PackagePath="README.md" />
	</ItemGroup>
</Project>